---
name: test-network-org2
version: 1.0.0
client:
  organization: Org2
  connection:
    timeout:
      peer:
        endorser: '300'
organizations:
  Org2:
    mspid: Org2MSP
    peers:
    - peer0.org2.example.com
    certificateAuthorities:
    - ca.org2.example.com
peers:
  peer0.org2.example.com:
    url: grpcs://localhost:9051
    tlsCACerts:
      pem: |
          -----BEGIN CERTIFICATE-----
          MIICHjCCAcWgAwIBAgIUG+TkrU0aQu4d5KZTPuWJO4aoXI8wCgYIKoZIzj0EAwIw
          bDELMAkGA1UEBhMCVUsxEjAQBgNVBAgTCUhhbXBzaGlyZTEQMA4GA1UEBxMHSHVy
          c2xleTEZMBcGA1UEChMQb3JnMi5leGFtcGxlLmNvbTEcMBoGA1UEAxMTY2Eub3Jn
          Mi5leGFtcGxlLmNvbTAeFw0yMTAzMTcwMjQwMDBaFw0zNjAzMTMwMjQwMDBaMGwx
          CzAJBgNVBAYTAlVLMRIwEAYDVQQIEwlIYW1wc2hpcmUxEDAOBgNVBAcTB0h1cnNs
          ZXkxGTAXBgNVBAoTEG9yZzIuZXhhbXBsZS5jb20xHDAaBgNVBAMTE2NhLm9yZzIu
          ZXhhbXBsZS5jb20wWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAR9BDfi8hzZyrYt
          Sntqt6BxaT7Ti6H6nRFfEEW/qVRxlMvBw16IZFp5ll6mGfVfKOR2K6h+ERC0RbMB
          Ggkm3zzXo0UwQzAOBgNVHQ8BAf8EBAMCAQYwEgYDVR0TAQH/BAgwBgEB/wIBATAd
          BgNVHQ4EFgQUvxbts3rw8Hln4JYe+HMAjezsb/AwCgYIKoZIzj0EAwIDRwAwRAIg
          bvj6cYdJRifAN1gxwjSeQmYhMb52n2ZneEdlfKNAxAoCICj4A2BoZUwI4CmZq6Lz
          LunHfefW+7xUWAitwtJRWtBx
          -----END CERTIFICATE-----
          
    grpcOptions:
      ssl-target-name-override: peer0.org2.example.com
      hostnameOverride: peer0.org2.example.com
certificateAuthorities:
  ca.org2.example.com:
    url: https://localhost:8054
    caName: ca-org2
    tlsCACerts:
      pem: 
        - |
          -----BEGIN CERTIFICATE-----
          MIICHjCCAcWgAwIBAgIUG+TkrU0aQu4d5KZTPuWJO4aoXI8wCgYIKoZIzj0EAwIw
          bDELMAkGA1UEBhMCVUsxEjAQBgNVBAgTCUhhbXBzaGlyZTEQMA4GA1UEBxMHSHVy
          c2xleTEZMBcGA1UEChMQb3JnMi5leGFtcGxlLmNvbTEcMBoGA1UEAxMTY2Eub3Jn
          Mi5leGFtcGxlLmNvbTAeFw0yMTAzMTcwMjQwMDBaFw0zNjAzMTMwMjQwMDBaMGwx
          CzAJBgNVBAYTAlVLMRIwEAYDVQQIEwlIYW1wc2hpcmUxEDAOBgNVBAcTB0h1cnNs
          ZXkxGTAXBgNVBAoTEG9yZzIuZXhhbXBsZS5jb20xHDAaBgNVBAMTE2NhLm9yZzIu
          ZXhhbXBsZS5jb20wWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAR9BDfi8hzZyrYt
          Sntqt6BxaT7Ti6H6nRFfEEW/qVRxlMvBw16IZFp5ll6mGfVfKOR2K6h+ERC0RbMB
          Ggkm3zzXo0UwQzAOBgNVHQ8BAf8EBAMCAQYwEgYDVR0TAQH/BAgwBgEB/wIBATAd
          BgNVHQ4EFgQUvxbts3rw8Hln4JYe+HMAjezsb/AwCgYIKoZIzj0EAwIDRwAwRAIg
          bvj6cYdJRifAN1gxwjSeQmYhMb52n2ZneEdlfKNAxAoCICj4A2BoZUwI4CmZq6Lz
          LunHfefW+7xUWAitwtJRWtBx
          -----END CERTIFICATE-----
          
    httpOptions:
      verify: false
